# Generated by Django 5.1.6 on 2026-06-14 13:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('key', models.SlugField(unique=True)),
                ('signing_secret', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_sources', to='tenants.organization')),
            ],
        ),
        migrations.CreateModel(
            name='InboundEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('event_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=120)),
                ('payload', models.JSONField()),
                ('normalized_payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('NORMALIZED', 'Normalized'), ('FAILED', 'Failed')], default='NORMALIZED', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='integrations.partnersource')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('signing_secret', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions', to='tenants.organization')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('DEAD_LETTER', 'Dead letter')], default='PENDING', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('response_code', models.PositiveIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='integrations.inboundevent')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='integrations.webhooksubscription')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='inboundevent',
            constraint=models.UniqueConstraint(fields=('source', 'idempotency_key'), name='unique_source_event_key'),
        ),
        migrations.AddConstraint(
            model_name='deliveryattempt',
            constraint=models.UniqueConstraint(fields=('event', 'subscription'), name='unique_event_subscription_delivery'),
        ),
    ]
